### PR TITLE
Tweak Option page

### LINKED ISSUE #9: オプション画面の見た目をもう少し良くする
参考資料？ サイトなんかを集めてデザイン側も少しやってみたい。

### PR DESCRIPTION
**Pull request by shyazusa**
close #9

### CODE REVIEW

**Comment by shyazusa** [comment]
@lodlock Sorry... I'm update README. I want to fix miss my english.
Please, OK?

**Comment by lodlock** [comment]
- Assign a label if desired. Multiple labels can be added using a comma separated list such as `it-news,security`.  Leave this field blank if you do not want to assign a label.

**Comment by shyazusa** [comment]
@lodlock Thank you!! very much!!

**Comment by shyazusa** [comment]
- [ ] #24 Kick out `undefined`

**Pull request merged**
